const path = require('path')
const webpack = require('webpack')
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

const banner = new webpack.BannerPlugin({
  banner: 'Do not edit this file directly. ' +
    'Instead, edit the files in the `src` folder and run in your terminal ' +
    '`npm run build`.'
});

module.exports = {

  entry: './src/index.js',

  output: {
    path: path.resolve(__dirname, 'assets')
  },

  module: {
    rules: [
      {
        test: /\.s[ac]ss$/i,
        use: [
          MiniCssExtractPlugin.loader,
          // Translates CSS into CommonJS
          'css-loader',
          // Compiles Sass to CSS
          'sass-loader'
        ],
      },
    ],
  },

  plugins: [
    new MiniCssExtractPlugin(),
    banner
  ]
}
