const path = require('path')
const webpack = require('webpack')
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

const banner = new webpack.BannerPlugin({
  banner: 'Do not edit this file directly. ' +
    'Instead, edit the files in the `src` folder and run in your terminal ' +
    '`npm run build`.'
});

module.exports = {

  entry: {
    main: './src/index.js',
    synchro: './src/synchro.js'
  } ,

  output: {
    path: path.resolve(__dirname, 'assets'),
    filename: '[name].bundle.js',
  },

  module: {
    rules: [
      {
        test: /\.(js)$/,
        exclude: /node_modules/,
        use: ['babel-loader']
      },
      {
        test: /\.s[ac]ss$/i,
        use: [
          MiniCssExtractPlugin.loader,
          'css-loader',
          'sass-loader'
        ],
      },
    ],
  },

  plugins: [
    new MiniCssExtractPlugin(),
    banner,
    new webpack.ProvidePlugin({
      "$":"jquery",
      "jQuery":"jquery",
      "window.jQuery":"jquery",
      "window.Tether": 'tether'
    })
  ],
  resolve: {
    alias: {
      "jquery-ui": "jquery-ui/jquery-ui.js"
    }
  }
}
